routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\GensetController;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::middleware(['auth:sanctum', 'verified'])->group(function () {
    Route::get('/', function () {
        return redirect()->route('gensets.create');
    });
    // Route::get('/transports/all', [TransportController::class, 'all'])->name('transports.all');
    Route::resource('gensets', GensetController::class);
    Route::get('/gensets/{genset}', [GensetController::class, 'show'])->name('gensets.show');
    // Route::get('/gensets/{id}', [GensetController::class, 'show'])->name('gensets.show');
    
    Route::get('/dashboard', function () {
        return view('dashboard');
    })->name('dashboard');
});

app/Models/Genset.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class Genset extends Model
{
    use HasFactory;

        /**
     * Get the user that owns the Transport
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Fortify\TwoFactorAuthenticatable;
use Laravel\Jetstream\HasProfilePhoto;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens;
    use HasFactory;
    use HasProfilePhoto;
    use Notifiable;
    use TwoFactorAuthenticatable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'username',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
        'two_factor_recovery_codes',
        'two_factor_secret',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    /**
     * The accessors to append to the model's array form.
     *
     * @var array
     */
    protected $appends = [
        'profile_photo_url',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/GensetController.php
<?php

namespace App\Http\Controllers;

use App\Models\Genset;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\View\View;

class GensetController extends Controller
{
    public function index()
    {
        $gensets = Genset::where('user_id', Auth::user()->id)->orderBy('created_at', 'DESC')->paginate();
        $pageTitle = "Record list";
        return view('gensets.index', compact('gensets', 'pageTitle'));
    }

    public function create()
    {
        return view('gensets.create');
    }

    public function show(Genset $genset)
    {
        return view('gensets.show', compact('genset'));
    }

    public function store(Request $request)
    {
        $genset = new Genset;
        $genset->id = $request->get('id');
        $genset->user_id = Auth::user()->id;
        $genset->speed = $request->get('speed');
        $genset->oil_pressure = $request->get('oil_pressure');
        $genset->coolant_temp = $request->get('coolant_temp');
        $genset->battery_volt = $request->get('battery_volt');
        $genset->run_time = $request->get('run_time');

        $genset->save();

        return redirect()->route('gensets.show', ['genset' => $genset] );
    }

    public function edit(Genset $genset)
    {
        return view('gensets.edit', compact('genset'));
    }

    public function update(Request $request, Genset $genset)
    {
        $genset->speed = $request->get('speed');
        $genset->oil_pressure = $request->get('oil_pressure');
        $genset->collant_temp = $request->get('collant_temp');
        $genset->battery_volt = $request->get('battery_volt');
        $genset->run_time = $request->get('run_time');
        $genset->save();

        return redirect()->route('gensets.index');
    }

    public function destroy(Genset $genset)
    {
        try {
            $genset->delete();
        } catch (\Throwable $th) {
            abort(500);
        }

        return redirect()->route('genset.index');
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

app/View/Components/GuestLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class GuestLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.guest');
    }
}

resources/views/dashboard.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Dashboard') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-xl sm:rounded-lg">
                <x-jet-welcome />
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/gensets/create.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Genset 1 - Engine Check') }}
        </h2>
    </x-slot>
        
    <form action="{{ route('gensets.store') }}" method="post">
        @csrf
        
        <div class="space-y-2">
            <div class="">
                <label class="block text-sm font-medium text-gray-700" for="speed">Speed</label>
                <input placeholder="example:1500" type="number" step="0.01" name="speed" class="block w-full mt-1 focus:ring-indigo-500 focus:border-indigo-500 border-gray-300 rounded">
            </div>
            <div class="">
                <label class="block text-sm font-medium text-gray-700" for="oil_pressure">Oil Pressure</label>
                <input type="number" step="0.01" name="oil_pressure" class="block w-full mt-1 focus:ring-indigo-500 focus:border-indigo-500 border-gray-300 rounded">
            </div>
            <div class="">
                <label class="block text-sm font-medium text-gray-700" for="coolant_temp">Coolant Temperature</label>
                <input type="number" step="0.01" name="coolant_temp" class="block w-full mt-1 focus:ring-indigo-500 focus:border-indigo-500 border-gray-300 rounded">
            </div>
            <div class="">
                <label class="block text-sm font-medium text-gray-700" for="battery_volt">Battery Voltage (Bar)</label>
                <input type="number" step="0.01" name="battery_volt" class="block w-full mt-1 focus:ring-indigo-500 focus:border-indigo-500 border-gray-300 rounded">
            </div>
            <div class="">
                <label class="block text-sm font-medium text-gray-700" for="run_time">Run Time</label>
                <input type="number" step="0.01" name="run_time" class="block w-full mt-1 focus:ring-indigo-500 focus:border-indigo-500 border-gray-300 rounded">
            </div>

        </div>
        <div class="mt-4">
            <button type="submit" id="submit" onclick="return derry();" class="block w-full text-center py-2 rounded-md bg-blue-500 text-white hover:bg-blue-600">Submit</button>
        </div>
    </form>
    
    <script>
        function derry(){
            if(confirm('dah yakin sama input nya bro?')){
                document.getElementById('submit').submit();
            } else{
                return false;
            }
        }
    </script>
    
    
</x-app-layout>

resources/views/gensets/edit.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Update Transport') }}
        </h2>
    </x-slot>
    
    @if ($errors->any())
    <div class="alert alert-danger">
        <strong>Whoops!</strong>Ada Eror, cek ulang! <br><br>
        <ul>
            @foreach ($errors->all() as $error)
            <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
    @endif
    
    <form action="{{ route('transports.update', $transport->id) }}" method="post">
        @csrf
        @method('PUT')
        
        <div class="space-y-2">
            <div class="">
                <label class="block text-sm font-medium text-gray-700" for="date_run">Date</label>
                <input type="date" value="{{ $transport->date_run->format('Y-m-d') }}" name="date_run" class="block w-full mt-1 focus:ring-indigo-500 focus:border-indigo-500 border-gray-300 rounded" Placeholder="date">
            </div>
            <div class="">
                <label class="block text-sm font-medium text-gray-700" for="vehicle">Vehicle</label>
                <select name="vehicle" id="vehicle" class="block w-full mt-1 focus:ring-indigo-500 focus:border-indigo-500 border-gray-300 rounded">
                    @foreach ($vehicles as $vehicle)
                        <option value="{{ $vehicle->id }}" {{ $transport->vehicle_id === $vehicle->id ? 'selected' : '' }}>{{ $vehicle->name }}</option>
                    @endforeach
                </select>
            </div>
            <div class="">
                <label class="block text-sm font-medium text-gray-700" for="purpose">Purpose</label>
                <select name="purpose" id="purpose" class="block w-full mt-1 focus:ring-indigo-500 focus:border-indigo-500 border-gray-300 rounded">
                    @foreach ($purposes as $purpose)
                        <option value="{{ $purpose->id }}" {{ $transport->purpose_id === $purpose->id ? 'selected' : '' }}>{{ $purpose->description }}</option>
                    @endforeach
                </select>
            </div>
            <div class="">
                <label class="block text-sm font-medium text-gray-700" for="from_time">From (Time)</label>
                <input type="time" value="{{ $transport->from_time->format('H:m') }}" step="60" name="from_time" class="block w-full mt-1 focus:ring-indigo-500 focus:border-indigo-500 border-gray-300 rounded">
            </div>
            <div class="">
                <label class="block text-sm font-medium text-gray-700" for="to_time">To (Time)</label>
                <input type="time" value="{{ $transport->to_time->format('H:m') }}" step="60" name="to_time" class="block w-full mt-1 focus:ring-indigo-500 focus:border-indigo-500 border-gray-300 rounded">
            </div>
            <div class="">
                <label class="block text-sm font-medium text-gray-700" for="km_before">(KM) Before</label>
                <input type="number" value="{{ $transport->km_before }}" name="km_before" class="block w-full mt-1 focus:ring-indigo-500 focus:border-indigo-500 border-gray-300 rounded">
            </div>
            <div class="">
                <label class="block text-sm font-medium text-gray-700" for="km_after">(KM) After</label>
                <input type="number" value="{{ $transport->km_after }}" name="km_after" class="block w-full mt-1 focus:ring-indigo-500 focus:border-indigo-500 border-gray-300 rounded">
            </div>
            <div class="">
                <label class="block text-sm font-medium text-gray-700" for="remarks">Remarks</label>
                <input type="text" value="{{ $transport->remarks }}" name="remarks" class="block w-full mt-1 focus:ring-indigo-500 focus:border-indigo-500 border-gray-300 rounded">
            </div>
        </div>
        <div class="mt-4">
            <button type="submit" class="block w-full text-center py-2 rounded-md bg-blue-500 text-white hover:bg-blue-600">Submit</button>
        </div>
    </form>
    
    
    
</x-app-layout>

resources/views/gensets/index.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ $pageTitle }}
        </h2>
    </x-slot>
    
    @if ($message = Session::get('success'))
    <div class="alert alert-sucess">
        <p>{{ $message }}</p>
    </div>
    @endif

    <div class="flex justify-end">
        <a href="{{ route('transports.create') }}" class="text-sm px-3 py-2 text-white bg-blue-500 rounded">Create new Transport</a>
    </div>
    
    <table class="table-auto w-full mt-2">
        <tr>
            <th class="px-1 py-1 border-b border-gray-300 text-xs">No</th>
            <th class="px-1 py-1 border-b border-gray-300 text-xs">Date Run</th>
            <th class="px-1 py-1 border-b border-gray-300 text-xs">Driver</th>
            <th class="px-1 py-1 border-b border-gray-300 text-xs">Vehicle</th>
            <th class="px-1 py-1 border-b border-gray-300 text-xs">Purpose</th>
            <th class="px-1 py-1 border-b border-gray-300 text-xs">(KM)Before</th>
            <th class="px-1 py-1 border-b border-gray-300 text-xs">(KM)After</th>
            <th class="px-1 py-1 border-b border-gray-300 text-xs">Total Run</th>
            <th class="px-1 py-1 border-b border-gray-300 text-xs">(Time) From</th>
            <th class="px-1 py-1 border-b border-gray-300 text-xs">(Time) To</th>
            <th class="px-1 py-1 border-b border-gray-300 text-xs">Remarks</th>
            <th class="px-1 py-1 border-b border-gray-300 text-xs">Action</th>
        </tr>
        
        @foreach ($transports as $transport )
        
        <tr>
            <td class="px-1 py-1 border-b border-gray-300 text-xs">{{ $loop->index + 1 }}</td>
            <td class="px-1 py-1 border-b border-gray-300 text-xs">{{ $transport->date_run->format('d/m/y') }}</td>
            <td class="px-1 py-1 border-b border-gray-300 text-xs">{{ $transport->user->name }}</td>
            <td class="px-1 py-1 border-b border-gray-300 text-xs">{{ $transport->vehicle->name }}</td>
            <td class="px-1 py-1 border-b border-gray-300 text-xs">{{ $transport->purpose->description }}</td>
            <td class="px-1 py-1 border-b border-gray-300 text-xs">{{ number_format($transport->km_before, 2) }}</td>
            <td class="px-1 py-1 border-b border-gray-300 text-xs">{{ number_format($transport->km_after, 2) }}</td>
            <td class="px-1 py-1 border-b border-gray-300 text-xs">{{ number_format($transport->km_after - $transport->km_before, 2) }}Km</td>
            <td class="px-1 py-1 border-b border-gray-300 text-xs">{{ $transport->from_time->format('H:m') }}</td>
            <td class="px-1 py-1 border-b border-gray-300 text-xs">{{ $transport->to_time->format('H:m') }}</td>
            <td class="px-1 py-1 border-b border-gray-300 text-xs">{{ $transport->remarks }}</td>
            <td class="px-1 py-1 border-b border-gray-300 text-xs">
                <form action="{{ route('transports.destroy', $transport->id) }}" method="post" class="flex">
                    <a href="{{ route('transports.edit', $transport->id) }}" class="">
                    <i><svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="#60A5FA">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z" />
                      </svg></i></a>
                    
                    @csrf
                    @method('DELETE')
                    
                    <button type="submit" class=""><i><svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="#DB2777">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
                      </svg></i></button>
                    
                </form>
            </td>
        </tr>
        @endforeach
    </table>
    
    {!! $transports->links() !!}
    
</x-app-layout>

resources/views/gensets/layout.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Transport Log</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.4.1/css/bootstrap-datepicker3.css"
    />
    
</head>
<body>
    <div class="container">
        <div class="con">
            @yield('content')
        </div>
    </div>
    <script
        type="text/javascript"
        src="https://code.jquery.com/jquery-1.11.3.min.js"
    ></script>
    <script
    type="text/javascript"
    src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.4.1/js/bootstrap-datepicker.min.js"
    ></script>
    <script>
        $(document).ready(function () {
          var date_input = $('input[name="date_run"]'); //our date input has the name "date"
          var container =
            $(".bootstrap-iso form").length > 0
              ? $(".bootstrap-iso form").parent()
              : "body";
          date_input.datepicker({
            format: "mm/dd/yyyy",
            container: container,
            todayHighlight: true,
            autoclose: true,
            clearBtn: true
          });
        });
    </script>
</body>
</html>

resources/views/gensets/show.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('List') }}
        </h2>
    </x-slot>
    
    
    <form action="{{ route('gensets.show', $genset->id) }}">
        <div class="row">
            <div class="">
                <div class="">
                    <Strong>Date:</Strong>
                    {{ $genset->created_at }}
                </div>
            </div>
            <div class="">
                <div class="">
                    <Strong>Speed:</Strong>
                    {{ $genset->oil_pressure }}
                </div>
            </div>
            <div class="">
                <div class="">
                    <Strong>Coolant Temperature</Strong>
                    {{ $genset->coolant_temp }}
                </div>
            </div>
            <div class="">
                <div class="">
                    <Strong>Battery Voltage</strong>
                    {{ $genset->battery_volt }}
                </div>
            </div>
            <div class="">
                <div class="">
                    <Strong>Run Time</Strong>
                    {{ $genset->run_time }}
                </div>
            </div>            
        </div>
    </form>
    
    
    
</x-app-layout>

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="csrf-token" content="{{ csrf_token() }}">

        <title>{{ config('app.name', 'Laravel') }}</title>
        <link rel="icon" href="{{ asset('images/logo.png') }}">

        <!-- Fonts -->
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Nunito:wght@400;600;700&display=swap">

        <!-- Styles -->
        <link rel="stylesheet" href="{{ mix('css/app.css') }}">

        @livewireStyles

        <!-- Scripts -->
        <script src="{{ mix('js/app.js') }}" defer></script>
        <style>
            .body-bg {
                background-color: #9921e8;
                background-image: linear-gradient(315deg, #9921e8 0%, #5f72be 74%)
            }
        </style>
    </head>
    <body class="font-sans antialiased">
        <x-jet-banner />

        <div class="min-h-screen bg-gray-100">
            @livewire('navigation-menu')

            <!-- Page Heading -->
            @if (isset($header))
                <header class="bg-white shadow">
                    <div class="max-w-7xl mx-auto py-6 px-4 sm:px-6 lg:px-8">
                        {{ $header }}
                    </div>
                </header>
            @endif

            <!-- Page Content -->
            <main class="py-12">
                <div class="max-w-7xl mx-auto sm:px-0 lg:px-0">
                    <div class="bg-white overflow-hidden shadow-xl sm:rounded-lg p-4">
                        {{ $slot }}
                    </div>
                </div>
            </main>
        </div>

        @stack('modals')

        @livewireScripts
    </body>
</html>

resources/views/layouts/guest.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="csrf-token" content="{{ csrf_token() }}">

        <title>{{ config('app.name', 'Laravel') }}</title>

        <!-- Fonts -->
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Nunito:wght@400;600;700&display=swap">

        <!-- Styles -->
        <link rel="stylesheet" href="{{ mix('css/app.css') }}">

        <!-- Scripts -->
        <script src="{{ mix('js/app.js') }}" defer></script>
    </head>
    <body>
        <div class="font-sans text-gray-900 antialiased">
            {{ $slot }}
        </div>
    </body>
</html>

resources/views/policy.blade.php
<x-guest-layout>
    <div class="pt-4 bg-gray-100">
        <div class="min-h-screen flex flex-col items-center pt-6 sm:pt-0">
            <div>
                <x-jet-authentication-card-logo />
            </div>

            <div class="w-full sm:max-w-2xl mt-6 p-6 bg-white shadow-md overflow-hidden sm:rounded-lg prose">
                {!! $policy !!}
            </div>
        </div>
    </div>
</x-guest-layout>

resources/views/terms.blade.php
<x-guest-layout>
    <div class="pt-4 bg-gray-100">
        <div class="min-h-screen flex flex-col items-center pt-6 sm:pt-0">
            <div>
                <x-jet-authentication-card-logo />
            </div>

            <div class="w-full sm:max-w-2xl mt-6 p-6 bg-white shadow-md overflow-hidden sm:rounded-lg prose">
                {!! $terms !!}
            </div>
        </div>
    </div>
</x-guest-layout>